[pytest]
pythonpath = .
testpaths = tests unit_tests
filterwarnings =
    error::pytest.PytestUnhandledThreadExceptionWarning
    error::pytest.PytestUnraisableExceptionWarning
    error::DeprecationWarning:app\..*
